refactor: move parse section to main function

diff --git a/git-cc b/git-cc
--- a/git-cc
+++ b/git-cc
@@ -54,47 +54,51 @@ prompt() {
   read -r -p 'Any breaking changes? List those changes: ' msg_breaking
 }
 
-while [ "${#}" -ge 1 ]; do
-  case "$1" in
-  --type)
-    msg_type="$2"
-    ;;
-  --subject)
-    msg_subject="$2"
-    ;;
-  --scope)
-    msg_scope="$2"
-    ;;
-  --body)
-    msg_body="$2"
-    ;;
-  --breaking)
-    msg_breaking="$2"
-    ;;
-  --dry-run)
-    dry_run=true
-    ;;
-  --interactive)
-    prompt
-    ;;
-  --help | -h | help)
-    usage && exit 0
-    ;;
-  --*)
-    echo 1>&2 "error: unknown option \`$1'" && usage && exit 1
-    ;;
-  -*)
-    echo 1>&2 "error: unknown switch \`$1'" && usage && exit 1
-    ;;
-  esac && shift
-done
+main() {
+  while [ "${#}" -ge 1 ]; do
+    case "$1" in
+    --type)
+      msg_type="$2"
+      ;;
+    --subject)
+      msg_subject="$2"
+      ;;
+    --scope)
+      msg_scope="$2"
+      ;;
+    --body)
+      msg_body="$2"
+      ;;
+    --breaking)
+      msg_breaking="$2"
+      ;;
+    --dry-run)
+      dry_run=true
+      ;;
+    --interactive)
+      prompt
+      ;;
+    --help | -h | help)
+      usage && exit 0
+      ;;
+    --*)
+      echo 1>&2 "error: unknown option \`$1'" && usage && exit 1
+      ;;
+    -*)
+      echo 1>&2 "error: unknown switch \`$1'" && usage && exit 1
+      ;;
+    esac && shift
+  done
 
-# check if subject provided
-[[ -z "${msg_subject:-}" ]] && echo 1>&2 "fatal: subject must be provided" && usage && exit 1
+  # check if subject provided
+  [[ -z "${msg_subject:-}" ]] && echo 1>&2 "fatal: subject must be provided" && usage && exit 1
 
-# print out commit on dry-run
-if (${dry_run:-false}); then
-  concat && exit 0
-else
-  git commit -m "$(concat)"
-fi
+  # print out commit on dry-run
+  if (${dry_run:-false}); then
+    concat && exit 0
+  else
+    git commit -m "$(concat)"
+  fi
+}
+
+main "${@}"
